version: "3"

services:
  carboncopydb:
    container_name: carboncopydb
    image: mysql/mysql-server:5.7
    env_file:
      - .env
    # Set max_allowed_packet to 256M
    command: --max_allowed_packet=32505856
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
